// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-kvarn-decode.cuh"

DECL_FATTN_KVARN_DECODE_CASE(128, 5, 2);
DECL_FATTN_KVARN_DECODE_CASE(256, 5, 2);
DECL_FATTN_KVARN_DECODE_CASE(512, 5, 2);
